services:
  app:
    build: ./
    command: bash -c "go test -v ./internal/database/* && go test -v ./internal/expression/* && ./calculating-server"
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_PASSWORD=secret

  db:
    image: postgres:latest
    restart: on-failure
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=secret
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10
